# Book settings
title: ENC2045 Computational Linguistics
author: Alvin Chen
logo: images/ntnu-word-2.png
copyright: "2020 Alvin Chen"
latex:
  latex_documents:
    targetname: book.tex

html:
    home_page_in_navbar: false
    extra_navbar: |
        <div style="text-align:center">
        <i class="fas fa-chalkboard-teacher fa-2x" style="color:Maroon;margin-right:5px"></i><a href="https://alvinntnu.github.io/NTNU_ENC2045/" target='_blank'>ENC2045 Course Website</a><br>
        <i class="fas fa-home fa-2x" style="color:Maroon;margin-right:5px"></i><a href="https://alvinchen.myftp.org/" target='_blank'>Alvin Chen's Homepage</a>
        </div>
only_build_toc_files: true
execute:
  execute_notebooks: auto
  exclude_patterns:
    - '*.ipynb'
    - 'exercise-ans/*.*'
    - 'temp/*.*'
bibtex_bibfiles:
   - book.bib
repository:
  url                       : https://github.com/alvinntnu/NTNU_ENC2045_LECTURES
  branch                    : main
launch_buttons:
  colab_url: "https://colab.research.google.com"

sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    
# Parse and render settings
parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    # - amsmath
    - colon_fence ## for ::: special contents
    # - deflist
    - dollarmath ## $ $$ for equations
    - html_admonition
    # - html_image
    - linkify ## auto-convert http into hyperlinks
    # - replacements
    # - smartquotes
    - substitution

  myst_url_schemes          : [mailto, http, https]  # URI schemes that will be recognised as external URLs in Markdown links

    